In [1]:
import pandas as pd
import os

os.chdir("C:/Users/Tngas/OneDrive/Documents/Python Projects/MVP Project/")

In [2]:
stats = pd.read_csv("player_mvp_stats - copy.csv", index_col=0)

In [3]:
stats

,Player,Pos,Age,Tm,G,GS,MP,FG,FGA,FG%,...,Pts Max,Share,Team,W,L,W/L%,GB,PS/G,PA/G,SRS
0,A.C. Green,PF,27,LAL,82,21,26.4,3.1,6.6,0.476,...,0.0,0.0,Los Angeles Lakers,58,24,0.707,5.0,106.3,99.6,6.73
1,Byron Scott,SG,29,LAL,82,82,32.1,6.1,12.8,0.477,...,0.0,0.0,Los Angeles Lakers,58,24,0.707,5.0,106.3,99.6,6.73
2,Elden Campbell,PF,22,LAL,52,0,7.3,1.1,2.4,0.455,...,0.0,0.0,Los Angeles Lakers,58,24,0.707,5.0,106.3,99.6,6.73
3,Irving Thomas,PF,25,LAL,26,0,4.2,0.7,1.9,0.340,...,0.0,0.0,Los Angeles Lakers,58,24,0.707,5.0,106.3,99.6,6.73
4,James Worthy,SF,29,LAL,78,74,38.6,9.2,18.7,0.492,...,0.0,0.0,Los Angeles Lakers,58,24,0.707,5.0,106.3,99.6,6.73
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
14087,Spencer Hawes,PF,28,MIL,54,1,14.8,2.5,5.1,0.484,...,0.0,0.0,Milwaukee Bucks,42,40,0.512,9.0,103.6,103.8,-0.45
14088,Steve Novak,PF,33,MIL,8,0,2.8,0.3,0.9,0.286,...,0.0,0.0,Milwaukee Bucks,42,40,0.512,9.0,103.6,103.8,-0.45
14089,Terrence Jones,PF,25,MIL,54,12,23.5,4.3,9.1,0.470,...,0.0,0.0,Milwaukee Bucks,42,40,0.512,9.0,103.6,103.8,-0.45
14090,Thon Maker,C,19,MIL,57,34,9.9,1.5,3.2,0.459,...,0.0,0.0,Milwaukee Bucks,42,40,0.512,9.0,103.6,103.8,-0.45
14091,Tony Snell,SG,25,MIL,80,80,29.2,3.1,6.8,0.455,...,0.0,0.0,Milwaukee Bucks,42,40,0.512,9.0,103.6,103.8,-0.45

In [4]:
# this looks pretty normal and expected. The null values make sense as they are are showing that a player did have anything recorded for that stats. For Example, some players did not 
# attempt 3pt shots or Free throws and therefore have a null for 3point percentage.

pd.isnull(stats).sum()

Player        0
Pos           0
Age           0
Tm            0
G             0
GS            0
MP            0
FG            0
FGA           0
FG%          50
3P            0
3PA           0
3P%        2042
2P            0
2PA           0
2P%          84
eFG%         50
FT            0
FTA           0
FT%         462
ORB           0
DRB           0
TRB           0
AST           0
STL           0
BLK           0
TOV           0
PF            0
PTS           0
Year          0
Pts Won       0
Pts Max       0
Share         0
Team          0
W             0
L             0
W/L%          0
GB            0
PS/G          0
PA/G          0
SRS           0
dtype: int64

In [5]:
stats[pd.isnull(stats["3P%"])][["Player", "3PA"]].head()

             Player  3PA
2    Elden Campbell  0.0
3     Irving Thomas  0.0
18       Jack Haley  0.0
20      Keith Owens  0.0
30  Benoit Benjamin  0.0

In [6]:
stats[pd.isnull(stats["FT%"])][["Player", "FTA"]].head()

              Player  FTA
77        John Coker  0.0
92      Jason Sasser  0.0
103  Adrian Caldwell  0.0
119     Bruno Šundov  0.0
158   Jamal Robinson  0.0

In [7]:
stats = stats.fillna(0)

In [8]:
stats.columns

Index(['Player', 'Pos', 'Age', 'Tm', 'G', 'GS', 'MP', 'FG', 'FGA', 'FG%', '3P',
       '3PA', '3P%', '2P', '2PA', '2P%', 'eFG%', 'FT', 'FTA', 'FT%', 'ORB',
       'DRB', 'TRB', 'AST', 'STL', 'BLK', 'TOV', 'PF', 'PTS', 'Year',
       'Pts Won', 'Pts Max', 'Share', 'Team', 'W', 'L', 'W/L%', 'GB', 'PS/G',
       'PA/G', 'SRS'],
      dtype='object')

In [9]:
# Removed Player name, position, Team, and the direct MVP columns as this would throw off the algorithm.
predictors = ['Age', 'G', 'GS', 'MP', 'FG', 'FGA', 'FG%', '3P',
       '3PA', '3P%', '2P', '2PA', '2P%', 'eFG%', 'FT', 'FTA', 'FT%', 'ORB',
       'DRB', 'TRB', 'AST', 'STL', 'BLK', 'TOV', 'PF', 'PTS', 'Year', 'W', 'L', 'W/L%', 'GB', 'PS/G',
       'PA/G', 'SRS']

In [10]:
train = stats[~(stats["Year"] < 2021)]
test = stats[stats["Year"] == 2021]

In [11]:
train.sort_values("Share", ascending=False).head(10)

,Player,Pos,Age,Tm,G,GS,MP,FG,FGA,FG%,...,Pts Max,Share,Team,W,L,W/L%,GB,PS/G,PA/G,SRS
641,Nikola Jokić,C,25,DEN,72,72,34.6,10.2,18.0,0.566,...,1010.0,0.961,Denver Nuggets,47,25,0.653,5.0,115.1,110.1,4.82
8624,Joel Embiid,C,26,PHI,51,51,31.1,9.0,17.6,0.513,...,1010.0,0.580,Philadelphia 76ers,49,23,0.681,0.0,113.6,108.1,5.28
3651,Stephen Curry,PG,32,GSW,63,63,34.2,10.4,21.7,0.482,...,1010.0,0.449,Golden State Warriors,39,33,0.542,12.0,113.7,112.7,1.10
9907,Giannis Antetokounmpo,PF,26,MIL,61,61,33.0,10.3,18.0,0.569,...,1010.0,0.345,Milwaukee Bucks,46,26,0.639,0.0,120.1,114.2,5.57
1389,Chris Paul,PG,35,PHO,70,70,31.4,6.3,12.6,0.499,...,1010.0,0.138,Phoenix Suns,51,21,0.708,0.0,115.3,109.5,5.67
10997,Luka Dončić,PG,21,DAL,66,66,34.3,9.8,20.5,0.479,...,1010.0,0.042,Dallas Mavericks,42,30,0.583,0.0,112.4,110.2,2.26
7464,Damian Lillard,PG,30,POR,67,67,35.8,9.0,19.9,0.451,...,1010.0,0.038,Portland Trail Blazers,42,30,0.583,10.0,116.1,114.3,1.81
3536,Julius Randle,PF,26,NYK,71,71,37.6,8.5,18.6,0.456,...,1010.0,0.020,New York Knicks,41,31,0.569,8.0,107.0,104.7,2.13
3531,Derrick Rose,PG,32,NYK,50,3,25.6,5.7,12.2,0.470,...,1010.0,0.010,New York Knicks,41,31,0.569,8.0,107.0,104.7,2.13
11358,Rudy Gobert,C,28,UTA,71,71,30.8,5.5,8.2,0.675,...,1010.0,0.008,Utah Jazz,52,20,0.722,0.0,116.4,107.2,8.97

In [12]:
test.sort_values("Share", ascending=False).head(10)

,Player,Pos,Age,Tm,G,GS,MP,FG,FGA,FG%,...,Pts Max,Share,Team,W,L,W/L%,GB,PS/G,PA/G,SRS
641,Nikola Jokić,C,25,DEN,72,72,34.6,10.2,18.0,0.566,...,1010.0,0.961,Denver Nuggets,47,25,0.653,5.0,115.1,110.1,4.82
8624,Joel Embiid,C,26,PHI,51,51,31.1,9.0,17.6,0.513,...,1010.0,0.580,Philadelphia 76ers,49,23,0.681,0.0,113.6,108.1,5.28
3651,Stephen Curry,PG,32,GSW,63,63,34.2,10.4,21.7,0.482,...,1010.0,0.449,Golden State Warriors,39,33,0.542,12.0,113.7,112.7,1.10
9907,Giannis Antetokounmpo,PF,26,MIL,61,61,33.0,10.3,18.0,0.569,...,1010.0,0.345,Milwaukee Bucks,46,26,0.639,0.0,120.1,114.2,5.57
1389,Chris Paul,PG,35,PHO,70,70,31.4,6.3,12.6,0.499,...,1010.0,0.138,Phoenix Suns,51,21,0.708,0.0,115.3,109.5,5.67
10997,Luka Dončić,PG,21,DAL,66,66,34.3,9.8,20.5,0.479,...,1010.0,0.042,Dallas Mavericks,42,30,0.583,0.0,112.4,110.2,2.26
7464,Damian Lillard,PG,30,POR,67,67,35.8,9.0,19.9,0.451,...,1010.0,0.038,Portland Trail Blazers,42,30,0.583,10.0,116.1,114.3,1.81
3536,Julius Randle,PF,26,NYK,71,71,37.6,8.5,18.6,0.456,...,1010.0,0.020,New York Knicks,41,31,0.569,8.0,107.0,104.7,2.13
3531,Derrick Rose,PG,32,NYK,50,3,25.6,5.7,12.2,0.470,...,1010.0,0.010,New York Knicks,41,31,0.569,8.0,107.0,104.7,2.13
11358,Rudy Gobert,C,28,UTA,71,71,30.8,5.5,8.2,0.675,...,1010.0,0.008,Utah Jazz,52,20,0.722,0.0,116.4,107.2,8.97

In [13]:
from sklearn.linear_model import Ridge

reg = Ridge(alpha=.1)

In [14]:
reg.fit(train[predictors],train["Share"])

Ridge(alpha=0.1)

In [15]:
predictions = reg.predict(test[predictors])
predictions = pd.DataFrame(predictions, columns=["predictions"], index=test.index)

In [16]:
predictions

       predictions
630      -0.004840
631      -0.016766
632       0.006319
633       0.013504
634       0.024497
...            ...
13897    -0.018654
13898    -0.002209
13899    -0.006021
13900    -0.002628
13901    -0.005231

[540 rows x 1 columns]

In [17]:
combination = pd.concat([test[["Player", "Share"]], predictions], axis=1)

In [18]:
combination.sort_values("Share", ascending=False).head(10)

                      Player  Share  predictions
641             Nikola Jokić  0.961     0.141560
8624             Joel Embiid  0.580     0.152123
3651           Stephen Curry  0.449     0.125944
9907   Giannis Antetokounmpo  0.345     0.122207
1389              Chris Paul  0.138     0.050144
10997            Luka Dončić  0.042     0.086712
7464          Damian Lillard  0.038     0.102868
3536           Julius Randle  0.020     0.054474
3531            Derrick Rose  0.010     0.001104
11358            Rudy Gobert  0.008     0.043057

In [19]:
from sklearn.metrics import mean_squared_error

mean_squared_error(combination["Share"], combination["predictions"])

0.0023387609045687897

In [20]:
combination["Share"].value_counts()

Share
0.000    525
0.001      3
0.961      1
0.138      1
0.010      1
0.020      1
0.449      1
0.005      1
0.038      1
0.003      1
0.580      1
0.345      1
0.042      1
0.008      1
Name: count, dtype: int64

In [21]:
actual = combination.sort_values("Share", ascending=False)
predicted = combination.sort_values("predictions", ascending=False)
actual["Rk"] = list(range(1,actual.shape[0]+1))
predicted["Predicted_Rk"] = list(range(1,predicted.shape[0]+1))

In [22]:
actual.merge(predicted, on="Player").head(5)

,Player,Share_x,predictions_x,Rk,Share_y,predictions_y,Predicted_Rk
0,Nikola Jokić,0.961,0.141560,1,0.961,0.141560,2
1,Joel Embiid,0.580,0.152123,2,0.580,0.152123,1
2,Stephen Curry,0.449,0.125944,3,0.449,0.125944,3
3,Giannis Antetokounmpo,0.345,0.122207,4,0.345,0.122207,4
4,Chris Paul,0.138,0.050144,5,0.138,0.050144,27

In [23]:
## AP = average precision
def find_ap(combination):
    actual = combination.sort_values("Share", ascending=False).head(5)
    predicted = combination.sort_values("predictions", ascending=False)
    ps = []
    found = 0
    seen = 1
    for index, row in predicted.iterrows():
        if row["Player"] in actual["Player"].values:
            found += 1
            ps.append(found / seen)
        seen += 1

    return sum(ps) / len(ps)

In [24]:
ap = find_ap(combination)

In [25]:
ap

0.837037037037037

In [26]:
years = list(range(1991, 2022))

In [27]:
aps = []
all_predictions = []
for year in years[5:]:
    train = stats[stats["Year"] < year]
    test = stats[stats["Year"] == year]
    reg.fit(train[predictors],train["Share"])
    predictions = reg.predict(test[predictors])
    predictions = pd.DataFrame(predictions, columns=["predictions"], index=test.index)
    combination = pd.concat([test[["Player", "Share"]], predictions], axis=1)
    all_predictions.append(combination)
    aps.append(find_ap(combination))

In [28]:
sum(aps)/ len(aps)

0.7112884360789578

In [29]:
def add_ranks(predictions):
    predictions = predictions.sort_values("predictions", ascending=False)
    predictions["Predicted_Rk"] = list(range(1,predictions.shape[0]+1))
    predictions = predictions.sort_values("Share", ascending=False)
    predictions["Rk"] = list(range(1,predictions.shape[0]+1))
    predictions["Diff"] = (predictions["Rk"] - predictions["Predicted_Rk"])
    return predictions

In [30]:
# 1997 season
add_ranks(all_predictions[1])

                Player  Share  predictions  Predicted_Rk   Rk  Diff
1600       Karl Malone  0.857     0.192318             2    1    -1
10524   Michael Jordan  0.832     0.167629             3    2    -1
908         Grant Hill  0.327     0.128646             6    3    -3
4682      Tim Hardaway  0.207     0.059984            20    4   -16
8248         Glen Rice  0.117     0.033110            53    5   -48
...                ...    ...          ...           ...  ...   ...
10136   Horacio Llamas  0.000     0.010171           156  437   281
3576     Ennis Whatley  0.000     0.010250           155  438   283
10594  Kevin Salvadori  0.000     0.010553           154  439   285
1138    Aaron Williams  0.000     0.010594           153  440   287
6792     Melvin Booker  0.000    -0.055185           441  441     0

[441 rows x 6 columns]

In [31]:
def backtest(stats, model, years, predictors):
    aps = []
    all_predictions = []
    for year in years:
        train = stats[stats["Year"] < year]
        test = stats[stats["Year"] == year]
        model.fit(train[predictors],train["Share"])
        predictions = model.predict(test[predictors])
        predictions = pd.DataFrame(predictions, columns=["predictions"], index=test.index)
        combination = pd.concat([test[["Player", "Share"]], predictions], axis=1)
        combination = add_ranks(combination)
        all_predictions.append(combination)
        aps.append(find_ap(combination))
    return sum(aps) / len(aps), aps, pd.concat(all_predictions)

In [32]:
mean_ap, aps, all_predictions = backtest(stats, reg, years[5:], predictors)

In [33]:
mean_ap

0.7112884360789578

In [34]:
all_predictions[all_predictions["Rk"] < 5].sort_values("Diff").head(10)

                Player  Share  predictions  Predicted_Rk  Rk  Diff
1224        Jason Kidd  0.712     0.028209            52   2   -50
5175        Steve Nash  0.839     0.034100            45   1   -44
8516   Peja Stojaković  0.228     0.036269            38   4   -34
12726      Joakim Noah  0.258     0.046968            37   4   -33
5193        Steve Nash  0.739     0.054128            34   1   -33
5208        Steve Nash  0.785     0.074421            21   2   -19
4682      Tim Hardaway  0.207     0.059984            20   4   -16
937      Allen Iverson  0.270     0.072120            14   4   -10
6746       Kobe Bryant  0.291     0.078014            14   4   -10
1157       Gary Payton  0.372     0.076708            13   3   -10

In [35]:
pd.concat([pd.Series(reg.coef_), pd.Series(predictors)], axis=1).sort_values(0, ascending=False)

           0     1
13  0.070002  eFG%
18  0.035041   DRB
29  0.027126  W/L%
17  0.021610   ORB
10  0.016945    2P
21  0.011635   STL
15  0.011351   FTA
22  0.011234   BLK
20  0.007456   AST
25  0.005893   PTS
4   0.005694    FG
5   0.005516   FGA
7   0.004569    3P
12  0.004083   2P%
0   0.000321   Age
30  0.000270    GB
27  0.000098     W
1   0.000092     G
2  -0.000006    GS
26 -0.000184  Year
32 -0.000219  PA/G
28 -0.000295     L
33 -0.000521   SRS
31 -0.000556  PS/G
24 -0.002634    PF
3  -0.004150    MP
16 -0.004575   FT%
14 -0.006585    FT
23 -0.009696   TOV
9  -0.009822   3P%
8  -0.010394   3PA
11 -0.017318   2PA
19 -0.027506   TRB
6  -0.135025   FG%

In [36]:
stat_ratios = stats[["PTS", "AST", "STL", "BLK", "3P", "Year"]].groupby("Year").apply(lambda x: x/x.mean())

In [50]:
stat_ratios

            PTS       AST       STL       BLK        3P  Year
0      1.013334  0.420714  0.961127  0.673469  0.508587   1.0
1      1.614653  1.028412  1.647646  0.673469  4.577279   1.0
2      0.311795  0.093492  0.274608  1.571429  0.000000   1.0
3      0.200440  0.186984  0.274608  0.000000  0.000000   1.0
4      2.383005  1.636110  1.784950  0.897959  1.525760   1.0
...         ...       ...       ...       ...       ...   ...
14087  1.207728  1.207491  0.971223  0.000000  2.393794   1.0
14088  0.257201  0.201248  0.647482  0.240964  0.099741   1.0
14089  1.274824  0.704370  1.133094  1.445783  1.695604   1.0
14090  0.279567  0.553433  0.323741  0.000000  0.099741   1.0
14091  0.559134  0.301873  0.485612  0.000000  0.598448   1.0

[14092 rows x 6 columns]

In [49]:
stat_ratios.index = stats.index
stats[["PTS_R", "AST_R", "STL_R", "BLK_R", "3P_R"]] = stat_ratios[["PTS", "AST", "STL", "BLK", "3P"]]

In [51]:
stats.head()

,Player,Pos,Age,Tm,G,GS,MP,FG,FGA,FG%,...,PS/G,PA/G,SRS,PTS_R,AST_R,STL_R,BLK_R,3P_R,NPos,NTm
0,A.C. Green,PF,27,LAL,82,21,26.4,3.1,6.6,0.476,...,106.3,99.6,6.73,1.013334,0.420714,0.961127,0.673469,0.508587,2,15
1,Byron Scott,SG,29,LAL,82,82,32.1,6.1,12.8,0.477,...,106.3,99.6,6.73,1.614653,1.028412,1.647646,0.673469,4.577279,12,15
2,Elden Campbell,PF,22,LAL,52,0,7.3,1.1,2.4,0.455,...,106.3,99.6,6.73,0.311795,0.093492,0.274608,1.571429,0.000000,2,15
3,Irving Thomas,PF,25,LAL,26,0,4.2,0.7,1.9,0.340,...,106.3,99.6,6.73,0.200440,0.186984,0.274608,0.000000,0.000000,2,15
4,James Worthy,SF,29,LAL,78,74,38.6,9.2,18.7,0.492,...,106.3,99.6,6.73,2.383005,1.636110,1.784950,0.897959,1.525760,8,15

In [52]:
predictors += ["PTS_R", "AST_R", "STL_R", "BLK_R", "3P_R"]

In [53]:
mean_ap, aps, all_predictions = backtest(stats, reg, years[5:], predictors)

In [55]:
mean_ap

0.7104869302852443

In [56]:
stats["Pos"].unique()

array(['PF', 'SG', 'SF', 'PG', 'C', 'PG-SG', 'PF-SF', 'SG-PG', 'PF-C',
       'SG-SF', 'SF-PF', 'SF-SG', 'C-PF', 'SG-PF', 'PG-SF', 'SF-C'],
      dtype=object)

In [41]:
stats["NPos"] = stats["Pos"].astype("category").cat.codes
stats["NTm"] = stats["Tm"].astype("category").cat.codes

In [42]:
from sklearn.ensemble import RandomForestRegressor

rf = RandomForestRegressor(n_estimators=50, random_state=1, min_samples_split=5)

mean_ap, aps, all_predictions = backtest(stats, rf, years[28:], predictors + ["NPos", "NTm"])

In [43]:
mean_ap

0.8109487734487734

In [44]:
from sklearn.preprocessing import StandardScaler

sc = StandardScaler()

In [45]:
def backtest(stats, model, years, predictors):
    aps = []
    all_predictions = []
    for year in years:
        train = stats[stats["Year"] < year].copy()
        test = stats[stats["Year"] == year].copy()
        sc.fit(train[predictors])
        train[predictors] = sc.transform(train[predictors])
        test[predictors] = sc.transform(test[predictors])
        model.fit(train[predictors],train["Share"])
        predictions = model.predict(test[predictors])
        predictions = pd.DataFrame(predictions, columns=["predictions"], index=test.index)
        combination = pd.concat([test[["Player", "Share"]], predictions], axis=1)
        combination = add_ranks(combination)
        all_predictions.append(combination)
        aps.append(find_ap(combination))
    return sum(aps) / len(aps), aps, pd.concat(all_predictions)

In [46]:
mean_ap, aps, all_predictions = backtest(stats, reg, years[28:], predictors)

In [47]:
mean_ap

0.7829437229437227